Repository TrnLeDuy/LIBRARY_MANAGEMENT, pull requests merged in 2023-04, with the labels that each got.

#43 Mobile App
  LibraryManagement2/.gitignore
  LibraryManagement2/.idea/.gitignore
  LibraryManagement2/.idea/.name
  LibraryManagement2/.idea/compiler.xml
  LibraryManagement2/.idea/gradle.xml
  LibraryManagement2/.idea/misc.xml
  LibraryManagement2/app/.gitignore
  LibraryManagement2/app/build.gradle
  LibraryManagement2/app/proguard-rules.pro
  LibraryManagement2/app/src/androidTest/java/com/example/librarymanagement/ExampleInstrumentedTest.java
  LibraryManagement2/app/src/main/AndroidManifest.xml
  LibraryManagement2/app/src/main/java/com/example/librarymanagement/MainActivity.java
  LibraryManagement2/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  LibraryManagement2/app/src/main/res/drawable/baseline_book_24.xml
  LibraryManagement2/app/src/main/res/drawable/baseline_search_24.xml
  LibraryManagement2/app/src/main/res/drawable/ic_launcher_background.xml
  LibraryManagement2/app/src/main/res/drawable/librarylogo.png
  LibraryManagement2/app/src/main/res/drawable/librarymanagementlogo.png
  LibraryManagement2/app/src/main/res/layout/activity_main.xml
  LibraryManagement2/app/src/main/res/layout/product_view.xml
  LibraryManagement2/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  LibraryManagement2/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  LibraryManagement2/app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  LibraryManagement2/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  LibraryManagement2/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  LibraryManagement2/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  LibraryManagement2/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  LibraryManagement2/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  LibraryManagement2/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  LibraryManagement2/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  LibraryManagement2/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  LibraryManagement2/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  LibraryManagement2/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  LibraryManagement2/app/src/main/res/values-night/themes.xml
  LibraryManagement2/app/src/main/res/values/colors.xml
  LibraryManagement2/app/src/main/res/values/strings.xml
  LibraryManagement2/app/src/main/res/values/themes.xml
  LibraryManagement2/app/src/main/res/xml/backup_rules.xml
  LibraryManagement2/app/src/main/res/xml/data_extraction_rules.xml
  LibraryManagement2/app/src/test/java/com/example/librarymanagement/ExampleUnitTest.java
  LibraryManagement2/build.gradle
  LibraryManagement2/gradle.properties
  LibraryManagement2/gradle/wrapper/gradle-wrapper.jar
  LibraryManagement2/gradle/wrapper/gradle-wrapper.properties
  LibraryManagement2/gradlew
  LibraryManagement2/gradlew.bat
  LibraryManagement2/settings.gradle
Labels: done

#47 Giao diện Quản lý
  Library_Management/App_Start/RouteConfig.cs
  Library_Management/Content/Site.css
  Library_Management/Content/mngestyle.css
  Library_Management/Controllers/EmployeeController.cs
  Library_Management/Controllers/LibrarianController.cs
  Library_Management/Controllers/ManagementController.cs
  Library_Management/Controllers/UserController.cs
  Library_Management/Library_Management.csproj
  Library_Management/Views/Employee/Books.cshtml
  Library_Management/Views/Employee/Borrows.cshtml
  Library_Management/Views/Employee/Readers.cshtml
  Library_Management/Views/Home/About.cshtml
  Library_Management/Views/Home/Contact.cshtml
  Library_Management/Views/Home/Index.cshtml
  Library_Management/Views/Librarian/Books.cshtml
  Library_Management/Views/Librarian/Borrows.cshtml
  Library_Management/Views/Librarian/Dashboard.cshtml
  Library_Management/Views/Librarian/Readers.cshtml
  Library_Management/Views/Management/Books.cshtml
  Library_Management/Views/Management/Borrows.cshtml
  Library_Management/Views/Management/Dashboard.cshtml
  Library_Management/Views/Management/Readers.cshtml
  Library_Management/Views/Management/Users.cshtml
  Library_Management/Views/Shared/_LayoutAdmin.cshtml
  Library_Management/Views/Shared/_LayoutEmployee.cshtml
  Library_Management/Views/Shared/_LayoutLibrarian.cshtml
  Library_Management/Views/User/LogIn.cshtml
Labels: done

#49 Insert data MySQL
  CNPM_QLTV.sql
Labels: done

#50 fix ActionLink for Librarian and Employee
  Library_Management/Views/Shared/_LayoutEmployee.cshtml
  Library_Management/Views/Shared/_LayoutLibrarian.cshtml
Labels: bug, done

#51 update database
  CNPM_QLTV.sql
Labels: enhancement
